#!/usr/bin/env python
import kas
import argparse
import os
import getpass


def check_owner(owner):
    '''
    checks if new owner is acceptable: so either phpuser or current KAS user
    :param owner: requested new owner
    :return: True if new owner name is accepatable, False if not
    '''
    if owner == "":
        return False
    if owner == "phpuser" or owner == kas.get_user():
        return True
    return False

if __name__ == "__main__":
    #version of this tool
    __version__ = "0.1"

    # get arguments from CLI
    parser = argparse.ArgumentParser(description='chown tool for hoster all-inkl.com using their KAS API, homepage: https://github.com/e-dschungel/kas_tools')
    parser.add_argument('-R', '--recursive', action='store_true', help='operate on files and directories recursively')
    parser.add_argument('owner')
    parser.add_argument('path', nargs = '*')
    parser.add_argument('--version', action='version', version = '%(prog)s ' + __version__)
    args = parser.parse_args()

    #make sure path is absolute
    args.path = [os.path.abspath(path) for path in args.path]

    #check input
    kas = kas.KAS()
    if not check_owner(args.owner):
        raise IOError("Invalid owner name!")
    for path in args.path:
        if not os.path.exists(path):
            raise IOError("{} does not exist".format(path))

    #get KAS user and password
    kas_user = kas.get_user();
    password = getpass.getpass("KAS password for user {}: ".format(kas_user))

    #log into KAS
    kas.login(kas_user, password)

    #execute chown
    for path in args.path:
        kas.update_chown(args.owner, kas.fix_chown_path(path), args.recursive)
